#!/usr/bin/env bash
# shellcheck disable=SC2154
# Updates package list, installs nginx, and adds a custom
# X-Served-By response header containing the server's hostname.

sudo apt update -y
sudo apt install nginx -y

echo "Holberton School for the win!" | sudo tee /var/www/html/index.html

sudo sed -i '/listen 80 default_server;/a\    add_header X-Served-By $hostname;' /etc/nginx/sites-available/default

sudo service nginx restart
