#!/usr/bin/env bash
# Updates package list, installs nginx, and configures a 301 redirect
# from /redirect_me to a YouTube video.

sudo apt update -y
sudo apt install nginx -y

echo "Holberton School for the win!" | sudo tee /var/www/html/index.html

sudo sed -i '/listen 80 default_server;/c\
listen 80 default_server;\
location /redirect_me {\
    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\
}' /etc/nginx/sites-available/default

sudo service nginx restart
