#!/usr/bin/env bash
# Updates package list, installs nginx, configures a redirect,
# and adds a custom 404 page.

sudo apt update -y
sudo apt install nginx -y

echo "Holberton School for the win!" | sudo tee /var/www/html/index.html

sudo sed -i '/listen 80 default_server;/a\    location /redirect_me { return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; }' /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

sudo sed -i '/listen 80 default_server;/a\    error_page 404 /404.html;' /etc/nginx/sites-available/default

sudo service nginx restart
